litreview_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from tickets.admin import admin_site




urlpatterns = [
    path('admin/', admin_site.urls),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('tickets/', include('tickets.urls')), 
    path('', include('pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView # ok




urlpatterns = [
    path('', HomePageView.as_view(), name='home'), # ok
   
]

profiles/urls.py
from django.urls import path

from .views import ProfileListView, ProfileDetailView, follow_unfollow_profile


app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='profile-list-view'),
    path('switch_follow/', follow_unfollow_profile, name='follow-unfollow-view'),
    path('<pk>/', ProfileDetailView.as_view(), name='profile-detail-view'),
]

tickets/urls.py
from django.urls import path

from .views import (
    TicketListView,
    TicketUpdateView,
    TicketDetailView, 
    TicketDeleteView,
    TicketCreateView,
    submit_review,
    # edit_review,
    tickets_of_following_profiles,
    my_feed_tickets_of_following_profiles,
    others_feed_tickets_of_following_profiles,
    user_search,
    
)

# app_name = 'tickets'

urlpatterns = [
    path('<int:pk>/edit/', TicketUpdateView.as_view(), name='ticket_edit'),
    path('<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),
    path('<int:pk>/delete/', TicketDeleteView.as_view(), name='ticket_delete'),
    path('new/', TicketCreateView.as_view(), name='ticket_new'),
    path('', TicketListView.as_view(), name='feed'), # 'ticket_list' replaced by 'feed'
    path('submit_review/<int:pk>/', submit_review, name='submit_review'),
    # path('edit_review/<int:pk>/', edit_review, name='edit_review'),
    path('account/', tickets_of_following_profiles, name='tickets-follow-view'),
    path('myfeed/', my_feed_tickets_of_following_profiles, name='myfeed'),
    path('othersfeed/', others_feed_tickets_of_following_profiles, name='othersfeed'),
    path('user_search/', user_search, name='user-search'),

]

tickets/models.py
from typing import Any
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from profiles.models import Profile



class Ticket(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('ticket_detail', args=[str(self.id)])

    class Meta:
        """ order tickets by ascending order using their titles, and by descending order as regard to their publication date"""
        
        ordering = ['-created', 'title']


################ CURRENTLY ######################

class ReviewRating(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    subject = models.CharField(max_length=128, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject
    
    # class Meta:
    #     constraints = [
    #         models.UniqueConstraint(fields=['ticket','user'],  name="unique_comments")
    #     ]
    ## or use this so that there can be only one ticket/user
        # unique_together = ('ticket', 'user', ) ## deprecated!!!

tickets/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

tickets/views.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
)

from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy

from django.template import loader
from django.db.models import Q
from django.core.paginator import Paginator

from .models import Ticket, ReviewRating
from profiles.models import Profile
from itertools import chain
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model 


from django.shortcuts import render, get_object_or_404, redirect
from .forms import ReviewForm
from django.contrib import messages

##

from crispy_forms.utils import render_crispy_form
from django.http import HttpResponse
from django.contrib.auth.models import User
##


class TicketListView(LoginRequiredMixin, ListView):
    model = Ticket
    template_name = 'feed.html' # 'ticket_list' replaced by 'feed'
    login_url = 'login'



class TicketDetailView(LoginRequiredMixin, DetailView):
    model = Ticket
    template_name = 'ticket_detail.html'
    login_url = 'login'


# class TicketUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
class TicketUpdateView(LoginRequiredMixin, UpdateView):
    model = Ticket
    fields = ('title', 'description', 'image')
    template_name = 'ticket_edit.html'
    login_url = 'login'

    def test_func(self):
        obj = self.get_object()
        return obj.author == Profile.objects.get(user=self.request.user)


class TicketDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Ticket
    template_name = 'ticket_delete.html'
    success_url = reverse_lazy('feed')
    login_url = 'login'

    def test_func(self):
        obj = self.get_object()
        return obj.author == Profile.objects.get(user=self.request.user)



class TicketCreateView(LoginRequiredMixin, CreateView):
    model = Ticket
    template_name = 'ticket_new.html'
    fields = ('title', 'description', 'image', )
    login_url = 'login'

    def form_valid(self, form):
        # form.instance.author = self.request.user
        form.instance.author = Profile.objects.get(user=self.request.user)
        return super().form_valid(form)


@login_required
def submit_review(request, pk):
    """review function"""
    url = request.META.get('HTTP_REFERER') # 'url' to redirect to 'ticket detail' page
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, ticket__id=pk)
            form = ReviewForm(request.POST, instance=reviews) # 'instance=reviews' is passed here to update review, not to create a new one
            form.save()
            messages.success(request, 'Merci. Votre critique a bien été actualisée!')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST) # form corresponds to a brand new review
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ticket_id = pk
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Merci. Votre critique a bien été envoyée!')
                return redirect(url)


@login_required
def tickets_of_following_profiles(request):
    """view for user dashboard"""
    # get logged-in user profile
    profile = Profile.objects.get(user=request.user)
    # check who's being followed
    users = [user for user in profile.following.all()]
    # initial value for variables
    tickets = []
    qs= None
    # get tickets of people we are following
    for dude in users:
        p = Profile.objects.get(user=dude)
        p_tickets = p.ticket_set.all()
        tickets.append(p_tickets)
    # get our own tickets
    my_tickets = profile.profiles_tickets()
    tickets.append(my_tickets)
    # sort and chain querysets and unpack the tickets list
    if len(tickets)>0:
        qs = sorted(chain(*tickets), reverse=True, key=lambda obj: obj.created)
    # get all users
    all_users = get_user_model().objects.values()
    context= {'profile':profile, 'tickets': qs, 'allusers': all_users}
    return render(request, 'tickets/main.html', context)


@login_required
def my_feed_tickets_of_following_profiles(request):
    """view for user dashboard"""
    # get logged-in user profile
    profile = Profile.objects.get(user=request.user)
    # check who's being followed
    users = [user for user in profile.following.all()]
    # initial value for variables
    tickets = []
    qs= None
    # get tickets of people we are following
    for dude in users:
        p = Profile.objects.get(user=dude)
        p_tickets = p.ticket_set.all()
        tickets.append(p_tickets)
    # get our own tickets
    my_tickets = profile.profiles_tickets()
    tickets.append(my_tickets)
    # sort and chain querysets and unpack the tickets list
    if len(tickets)>0:
        qs = sorted(chain(*tickets), reverse=True, key=lambda obj: obj.created)
    # get all users
    all_users = get_user_model().objects.values()
    context= {'profile':profile, 'tickets': qs, 'allusers': all_users}
    return render(request, 'tickets/myfeed.html', context)


@login_required
def others_feed_tickets_of_following_profiles(request):
    """view for other users feed"""
    # get logged-in user profile
    profile = Profile.objects.get(user=request.user)
    # check who's being followed
    users = [user for user in profile.following.all()]
    # initial value for variables
    tickets = []
    qs= None
    # get tickets of people we are following
    for dude in users:
        p = Profile.objects.get(user=dude)
        p_tickets = p.ticket_set.all()
        tickets.append(p_tickets)
    # get our own tickets
    my_tickets = profile.profiles_tickets()
    tickets.append(my_tickets)
    # sort and chain querysets and unpack the tickets list
    if len(tickets)>0:
        qs = sorted(chain(*tickets), reverse=True, key=lambda obj: obj.created)
    # get all users
    all_users = get_user_model().objects.values()
    context= {'profile':profile, 'tickets': qs, 'allusers': all_users}
    return render(request, 'tickets/othersfeed.html', context)


@login_required
def user_search(request):
    """search bar"""
    if request.method == "POST":
        searched = request.POST['searched']
        users = get_user_model().objects.filter(username__contains=searched).exclude(username=request.user) # Good good
        return render(request, 'tickets/user_search.html', {'searched':searched, 'users':users})
    else:
        return render(request, 'tickets/user_search.html', {} )

tickets/templates/tickets/main.html
<!-- templates/home.html -->
{% extends 'base.html' %}


{% load static %}

{% block title %}
Posts
{% endblock title %}


{% block content %}

<!-- PLEASE DO NOT ERASE ANY COMMENTS __ KEEP THEM FOR FUTURE REF -->

<br><br>
<div class="container">
    <div class="row">
        <div class="col-6">
            <!-- search bar -->
            <form class="form-inline pull-right" method=POST action="{% url 'user-search' %}">
                {% csrf_token %}
                <input class="form-control mr-sm-2" name="searched" type="search" placeholder="Nom d'utilisateur..." value="{{ request.GET.q }}" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Envoyer</button>
            </form>
        </div>
        <div class="col-6 text-center">
            <!-- CREATE TICKET + ADD REVIEW -->
            <a type="btn" href="{% url 'ticket_new' %}" class="btn btn-warning">Demander et Créer Une Critique</a>
        </div>
    </div>
</div>
<br><br>

<!-- User content -->
<hr>
<div class="container">
    <div class="row">
        
        <!-- LIST OF FOLLOWED PEOPLE AND FOLLOWERS -->
        <div class="col-3">
            Bonjour <b>{{ profile|capfirst }}</b>
            <br><br>
            <a href="{% url 'profiles:profile-list-view' %}">
                <button type="button" class="btn btn-primary">Gérer Mes Abonnements</button>
            </a>
            <hr><hr>
            Mes Abonnements (Following):
            <ul>
                {% for p in profile.following.all %}
                <li>{{ p|capfirst }}</li>
                {% endfor %}
            </ul>
            <hr>
            <hr>
            Mes Abonnés (Followers): <br>
            <ul>
                {% for follower in user.following.all %}
                <li>{{ follower|capfirst }}</li>
                {% endfor %}
            </ul>
        </div>
        
        <!-- CURRENT USER CONTENT -->
        <div class="col-9">
            <h2 class="display-4">Mes Posts</h2>
            <hr>
            {% for t in tickets %}
                
                {% if profile == t.author %}
                    <span class="text-muted float-right" style="font-size:0.7rem;">
                        Publié par {{ profile }} à {{t.created|date:"H:i"}}, le {{t.created|date:"d b Y"}}
                    </span>
                    
                    <!-- Auteur: {{t.author}} -->
                    <p style="font-weight: bolder; color:yellowgreen;">Titre: {{t.title}}</p>

                    <!-- REVIEW STARTS HERE -->
                    {% if t.comments.first %}
                    <p style="margin-bottom:0;">
                                
                        {% if profile == t.comments.first.user %}
                            <span class="text-muted">Vous avez publié une critique</span><br>
                        {% else %}
                            <span class="text-muted">{{ t.comments.first.user }} a publié une critique</span><br>
                        {% endif %}

                        <span class="font-weight-bold font-italic">{{ t.comments.first.subject }}&nbsp;&nbsp;-&nbsp;&nbsp;</span>
                        <span class="fa {% if t.comments.first.rating >= 1 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                        <span class="fa {% if t.comments.first.rating >= 2 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                        <span class="fa {% if t.comments.first.rating >= 3 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                        <span class="fa {% if t.comments.first.rating >= 4 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                        <span class="fa {% if t.comments.first.rating >= 5 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                        <span>&nbsp;&nbsp;-&nbsp;&nbsp;</span>
                        <span class="font-weight-bold font-italic">'{{ t.comments.first.review}}'</span>
                    </p>
                    {% endif %}
                    <!-- REVIEW ENDS HERE -->

                    <br>
                    <p style="background-color:rgba(0,0,0,.03);padding: 10px;">{{t.description}}</p>
                    
                    {% if t.image %}
                    <img class="image" src="/static/images/{{ t.image }}"  alt="livre ou article" style="max-width: 300px;"/>
                    {% endif %}
                    <br>
                    
                    {% if user == t.author.user %}
                        <a href="{% url 'ticket_edit' t.pk %}">Modifier</a> |
                        <a href="{% url 'ticket_delete' t.pk %}">Effacer</a>
                    {% endif %}
                    <br>
                    {% if not t.comments.first %}
                        <a type="btn" href="{% url 'ticket_detail' t.pk %}" class="btn btn-outline-primary pull-right">Créer une critique</a><br><br>
                    {% endif %}

                    <hr>
                {% endif %}
            {% endfor %}
        </div>
        
        
    </div>
</div>
{% endblock content %}

tickets/templates/tickets/myfeed.html
<!-- templates/home.html -->
{% extends 'base.html' %}


{% load static %}

{% block title %}
Flux
{% endblock title %}


{% block content %}

<!-- PLEASE DO NOT ERASE ANY COMMENTS __ KEEP THEM FOR FUTURE REF -->
<br><br>
<div class="container">
    <div class="row">
        <div class="col-6">
            <!-- search bar -->
            <form class="form-inline pull-right" method=POST action="{% url 'user-search' %}">
                {% csrf_token %}
                <input class="form-control mr-sm-2" name="searched" type="search" placeholder="Nom d'utilisateur..." value="{{ request.GET.q }}" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Envoyer</button>
            </form>
        </div>
        <div class="col-6 text-center">
            <!-- CREATE TICKET + ADD REVIEW -->
            <a type="btn" href="{% url 'ticket_new' %}" class="btn btn-warning">Demander et Créer Une Critique</a>
        </div>
    </div>
</div>
<br><br>

<!-- User content -->
<hr>
<div class="container">
    <div class="row">
        
        <!-- LIST OF FOLLOWED PEOPLE AND FOLLOWERS -->
        <div class="col-3">
            Bonjour <b>{{ profile|capfirst }}</b>
            <br><br>
            <a href="{% url 'profiles:profile-list-view' %}">
                <button type="button" class="btn btn-primary">Gérer Mes Abonnements</button>
            </a>
            <hr><hr>
            Mes Abonnements (Following):
            <ul>
                {% for p in profile.following.all %}
                <li>{{ p|capfirst }}</li>
                {% endfor %}
            </ul>
            <hr>
            <hr>
            Mes Abonnés (Followers): <br>
            <ul>
                {% for follower in user.following.all %}
                <li>{{ follower|capfirst }}</li>
                {% endfor %}
            </ul>
        </div>
        
        <!-- CURRENT USER CONTENT -->
        <div class="col-9">
            <h2 class="display-4">Flux</h2>
            <hr>
            {% for t in tickets %}
                
                {% if profile == t.author %}
                    <span class="text-muted float-right" style="font-size:0.7rem;">
                        Publié par {{ profile }} à {{t.created|date:"H:i"}}, le {{t.created|date:"d b Y"}}
                    </span>
                    
                    <!-- Auteur: {{t.author}} -->
                    <p style="font-weight: bolder; color:yellowgreen;">Titre: {{t.title}}</p>

                    <!-- REVIEW STARTS HERE -->
                    {% if t.comments.first %}
                    <p style="margin-bottom:0;">
                                
                        {% if profile == t.comments.first.user %}
                            <span class="text-muted">Vous avez publié une critique</span><br>
                        {% else %}
                            <span class="text-muted">{{ t.comments.first.user }} a publié une critique</span><br>
                        {% endif %}

                        <span class="font-weight-bold font-italic">{{ t.comments.first.subject }}&nbsp;&nbsp;-&nbsp;&nbsp;</span>
                        <span class="fa {% if t.comments.first.rating >= 1 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                        <span class="fa {% if t.comments.first.rating >= 2 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                        <span class="fa {% if t.comments.first.rating >= 3 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                        <span class="fa {% if t.comments.first.rating >= 4 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                        <span class="fa {% if t.comments.first.rating >= 5 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                        <span>&nbsp;&nbsp;-&nbsp;&nbsp;</span>
                        <span class="font-weight-bold font-italic">'{{ t.comments.first.review}}'</span>
                    </p>
                    {% endif %}
                    <!-- REVIEW ENDS HERE -->

                    <br>
                    <p style="background-color:rgba(0,0,0,.03);padding: 10px;">{{t.description}}</p>
                    
                    {% if t.image %}
                    <img class="image" src="/static/images/{{ t.image }}"  alt="livre ou article" style="max-width: 300px;"/>
                    {% endif %}
                    <br>
                    
                    {% if user == t.author.user %}
                        <a href="{% url 'ticket_edit' t.pk %}">Modifier</a> |
                        <a href="{% url 'ticket_delete' t.pk %}">Effacer</a>
                    {% endif %}
                    <br>
                    {% if not t.comments.first %}
                        <a type="btn" href="{% url 'ticket_detail' t.pk %}" class="btn btn-outline-primary pull-right">Créer une critique</a><br><br>
                    {% endif %}

                    <hr>
                {% endif %}
            {% endfor %}
            <!-- </div> -->
        
            <!-- NETWORK USERS CONTENTS -->
            <!-- <div class="col-5"> -->
            <hr><hr>
            <h2 class="display-4">Tickets Réseau</h2>
            <hr>
            {% for t in tickets %}
                {% if profile != t.author %}
                    <span class="text-muted float-right" style="font-size:0.7rem;">
                        Publié par {{ t.author }} à {{t.created|date:"H:i"}}, le {{t.created|date:"d b Y"}}
                    </span>
                    
                    <!-- Auteur: {{t.author}} -->
                    <b>Titre: {{t.title}}</b><br><br>
                    
                    <!-- REVIEW STARTS HERE -->
                    {% if t.comments.first %}
                        <p style="margin-bottom:0;">
                                    
                            {% if profile == t.comments.first.user %}
                                <span class="text-muted">Vous avez publié une critique</span><br>
                            {% else %}
                                <span class="text-muted">{{ t.comments.first.user }} a publié une critique</span><br>
                            {% endif %}

                            <span class="font-weight-bold font-italic">{{ t.comments.first.subject }}&nbsp;&nbsp;-&nbsp;&nbsp;</span>
                            <span class="fa {% if t.comments.first.rating >= 1 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                            <span class="fa {% if t.comments.first.rating >= 2 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                            <span class="fa {% if t.comments.first.rating >= 3 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                            <span class="fa {% if t.comments.first.rating >= 4 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                            <span class="fa {% if t.comments.first.rating >= 5 %} fa-star {% else %} fa-star-o {% endif%}"></span>
                            <span>&nbsp;&nbsp;-&nbsp;&nbsp;</span>
                            <span class="font-weight-bold font-italic">'{{ t.comments.first.review}}'</span>
                        </p>
                    {% endif %}
                    <!-- REVIEW ENDS HERE -->

                    <br>
                    {{t.description}}
                    <br>
                    
                    {% if t.image %}
                    <img class="image" src="/static/images/{{ t.image }}"  alt="livre ou article" style="max-width: 300px;"/>
                    {% endif %}
                    <br>
                    
                    {% if user == t.author.user %}
                        <a href="{% url 'ticket_edit' t.pk %}">Modifier</a> |
                        <a href="{% url 'ticket_delete' t.pk %}">Effacer</a>
                    {% endif %}

                    <br>
                    {% if not t.comments.first %}
                        <a type="btn" href="{% url 'ticket_detail' t.pk %}" class="btn btn-outline-primary pull-right">Créer une critique</a><br><br>
                    {% endif %}
                    
                    <hr>
                {% endif %}
            
            {% endfor %}
            <!-- <a type="btn" href="{% url 'feed' %}" class="btn ml-2 btn-primary">Voir tous les tickets</a> -->
            <a type="btn" href="{% url 'profiles:profile-list-view' %}" class="btn ml-2 btn-primary">Voir tous les utilisateurs</a><br><br>
        </div>
        
    </div>
</div>
{% endblock content %}

tickets/templates/tickets/othersfeed.html
<!-- templates/home.html -->
{% extends 'base.html' %}


{% load static %}

{% block title %}
Main Posts
{% endblock title %}


{% block content %}

<!-- search bar -->
<br><br>
<div class="container ">
    <form class="form-inline pull-right" method=POST action="{% url 'user-search' %}">
        {% csrf_token %}
        <input class="form-control mr-sm-2" name="searched" type="search" placeholder="Taper le nom d'un utilisateur" value="{{ request.GET.q }}" aria-label="Search">
        <button class="btn btn-primary my-2 my-sm-0" type="submit">Chercher</button>
    </form>
</div>
<br><br><br>

<!-- CREATE TICKET + ADD REVIEW -->
<div class="text-center">
    <a type="btn" href="{% url 'ticket_new' %}" class="btn btn-primary">Demander et Créer Une Critique</a>
</div>
<br/>

<!-- User content -->
<hr>
<div class="container">
    <div class="row">
        
        <!-- LIST OF FOLLOWED PEOPLE AND FOLLOWERS -->
        <div class="col-3">
            <b>{{ profile|upper }}</b> suit:
            <hr>
            <ul>
                {% for p in profile.following.all %}
                <li>{{p}}</li>
                {% endfor %}
            </ul>
            <hr>
            <hr>
            <b>{{ profile|upper }}</b> est suivi par:
            <hr>
            <ul>
                {% for follower in user.following.all %}
                <li>{{follower}}</li>
                {% endfor %}
            </ul>
        </div>
        
        <!-- FOLLOWED PEOPLE CONTENT -->
        <div class="col-9">
            <h3 class="display-4">Tickets Followers & Following</h3>
            <hr>
            {% for t in tickets %}
                {% if profile != t.author %}
                <span class="text-muted float-right" style="font-size:0.7rem;">
                    {{t.created|date:"H:i"}}, {{t.created|date:"d b Y"}}
                </span>
                
                Auteur: {{t.author}}
                <br>
                <b>Titre: {{t.title}}</b>
                
                <br><br>
                {{t.description}}
                <br><br>
                
                {% if t.image %}
                <img class="image" src="/static/images/{{ t.image }}"  alt="livre ou article" style="max-width: 300px;"/>
                {% endif %}
                <br><br>
                
                {% if user == t.author.user %}
                    <a href="{% url 'ticket_edit' t.pk %}">Modifier</a> |
                    <a href="{% url 'ticket_delete' t.pk %}">Effacer</a>
                {% endif %}
                
                <hr>
                {% endif %}
            {% endfor %}
        </div>
        
    </div>
</div>
{% endblock content %}

tickets/templates/tickets/user_search.html
<!-- templates/home.html -->
{% extends 'base.html' %}


{% block title %}
Main Posts
{% endblock title %}


{% block content %}
<!-- PLEASE DO NOT ERASE ANY COMMENTS __ KEEP THEM FOR FUTURE REF -->

<br><br>
<div class="container">
    <div class="row">
        <div class="col-6">
            <!-- search bar -->
            <form class="form-inline pull-right" method=POST action="{% url 'user-search' %}">
                {% csrf_token %}
                <input class="form-control mr-sm-2" name="searched" type="search" placeholder="Nom d'utilisateur..." value="{{ request.GET.q }}" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Envoyer</button>
            </form>
        </div>
        <div class="col-6 text-center">
            <!-- CREATE TICKET + ADD REVIEW -->
            <a type="btn" href="{% url 'ticket_new' %}" class="btn btn-warning">Demander et Créer Une Critique</a>
        </div>
    </div>
</div>
<br><br>

<hr>
Résultats de votre recherche
<hr>
    {% if searched %}
        <h6>Vous avez tapé: {{ searched }} </h6>
        {% for user in users %}
            {% if not profile %}
            <!-- <h6>{{user}}: ID°{{user.id}} // {{ user.date_joined}} // {{ user.profile.id}}</h6> -->
            <!-- <a type="btn" href="{% url 'profiles:profile-detail-view' user.profile.id %}" class="btn btn-primary">Voir profil</a><br> -->
            <br><a href="{% url 'profiles:profile-detail-view' user.profile.id %}">{{user}}</a><br>
            {% endif%}
        {% endfor %}
    {% else %}
        <h6>Merci d'entrer votre recherche dans la barre ci-dessus, svp. </h6> 
    {% endif %}

{% endblock content %}