litreview_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from tickets.admin import admin_site




urlpatterns = [
    path('admin/', admin_site.urls),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('tickets/', include('tickets.urls')), 
    path('', include('pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView # ok




urlpatterns = [
    path('', HomePageView.as_view(), name='home'), # ok
   
]

profiles/urls.py
from django.urls import path

from .views import ProfileListView, ProfileDetailView, follow_unfollow_profile


app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='profile-list-view'),
    path('switch_follow/', follow_unfollow_profile, name='follow-unfollow-view'),
    path('<pk>/', ProfileDetailView.as_view(), name='profile-detail-view'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    following = models.ManyToManyField(to=settings.AUTH_USER_MODEL, related_name='following', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def profiles_tickets(self):
        return self.ticket_set.all()

    def __str__(self):
        return str(self.user.username)

    class Meta:
        ordering = ('-created',)

    # class Meta:
    #     constraints = [
    #         models.UniqueConstraint(fields=['user','following'],  name="unique_comments")
    #     ]
    ## or use so that there can be only one ticket/user
        # unique_together = ('user', 'following', ) ## deprecated!!!

profiles/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
)


@login_required
def follow_unfollow_profile(request):
    """function to unfollow"""
    if request.method=="POST":
        my_profile = Profile.objects.get(user=request.user)
        pk = request.POST.get('profile_pk')
        obj = Profile.objects.get(pk=pk)
        if obj.user in my_profile.following.all():
            my_profile.following.remove(obj.user)
        else:
            my_profile.following.add(obj.user)
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:profile-list-view')
    

class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/main.html'
    context_object_name = 'profiles' # object_list as default
    login_url = 'login'

    def get_queryset(self):
        # getting all the profiles w/o the one that belongs to the logged-in user
        return Profile.objects.all().exclude(user=self.request.user)


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'profiles/detail.html'
    login_url = 'login'

    def get_object(self, **kwargs):
        pk = self.kwargs.get('pk')
        view_profile = Profile.objects.get(pk=pk)
        return view_profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        view_profile = self.get_object()
        my_profile = Profile.objects.get(user=self.request.user)
        if view_profile.user in my_profile.following.all():
            follow = True
        else:
            follow = False
        context["follow"] = follow
        return context

profiles/templates/profiles/_user_search.html
<!-- templates/home.html -->
{% extends 'base.html' %}


{% block title %}
Main Posts
{% endblock title %}


{% block content %}

<!-- search bar -->
<br><br>
<div class="container">
    <form class="form-inline" method="POST" action="{% url 'usersearch' %}">
        {% csrf_token %}
        <input class="form-control mr-sm-2" name="searched" type="search" placeholder="Nom d'utilisateur..." value="{{ request.GET.q }}" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Envoyer</button>
    </form>
</div>
<br>
Searched users:
{% if searched %}
    <h1>You Searched for ... </h1>
{% else %}
    <h1>Sorry! It doesn't work yet... </h1> 
{% endif%}


{% endblock content %}

profiles/templates/profiles/detail.html
{% extends 'base.html' %}


{% block title %}Détail Profil{% endblock title %}


{% block content %}

<!-- add a modal -->

<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Souhaitez-vous suivre {{object}} ?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>En cliquant sur 'Confirmer' vous pourrez voir les tickets publiés par {{object}}.</p>
            </div>
            <div class="modal-footer">
                <form action="{% url 'profiles:follow-unfollow-view' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="btn btn-success">Confirmer</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="container">

    <div class="row">
        <div class="col-3">
            {{object}}
            <hr>
            {% if follow %}
                <form action="{% url 'profiles:follow-unfollow-view' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="btn btn-danger"> Unfollow</button>
                </form>
            {% else %}
                <button id="follow-btn" class="btn btn-success">Follow</button>
            {% endif %}
            <hr>
            <br><br>
            <a type="btn" onClick="javascript:history.go(-1);" class="btn btn-warning btn-sm">Retourner</a><br>
        </div>
        <div class="col-9">
            {% for ticket in object.profiles_tickets %}
                <b>{{ticket.title}}</b>
                <span class="text-muted float-right" style="font-size:0.7rem;">{{ ticket.created|date:"H:i" }}, {{ ticket.created|date:"d b Y" }}</span>
                <br>
                {{ticket.description}}
                <br>
                <hr>
            {% endfor %}
        </div>
    </div>

</div>
            
            
            
{% endblock content %}

{% block scripts %}
    <!-- this script enables the following modal -->
    <script>
        $(document).ready(function(){
            $('#follow-btn').click(function(){
                $('.modal')
                .modal('show')
            })
        })
    </script>
{% endblock scripts %}

profiles/templates/profiles/main.html
{% extends 'base.html' %}


{% block title %}
    Gestion Des Abonnements
{% endblock title %}


{% block content %}

    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-6">
                <!-- search bar -->
                <form class="form-inline pull-right" method=POST action="{% url 'user-search' %}">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" name="searched" type="search" placeholder="Nom d'utilisateur..." value="{{ request.GET.q }}" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Envoyer</button>
                </form>
            </div>
            <div class="col-6 text-center">
                <!-- CREATE TICKET + ADD REVIEW -->
                <a type="btn" href="{% url 'ticket_new' %}" class="btn btn-warning">Demander et Créer Une Critique</a>
            </div>
        </div>
    </div>
    
    <br><br>
    <hr>
    <br><br>
    <div class="container">
        <div class="row">
            <!-- LIST OF FOLLOWED PEOPLE AND FOLLOWERS -->
            <div class="col-6">
                Bonjour <b>{{ user|capfirst }}</b>
                <br><br>
                <br>
                <a type="btn" onClick="javascript:history.go(-1);" class="btn btn-warning btn-sm">Retourner</a><br><br><br>
            </div>

            <!-- USERS LIST -->
            <div class="col-6">
                <h3>Liste des utilisateurs du site.</h3>
                <span class="text-muted" style="font-size:1rem;">
                    Cliquer sur un nom pour gérer votre abonnement avec cet utilisateur.
                </span><br><br><br>
                {% for profile in profiles %}
                    <div>
                        <a href="{% url 'profiles:profile-detail-view' profile.pk %}">{{ profile|capfirst }}</a><br>
                        <!-- <a type="btn" href="{% url 'profiles:profile-detail-view' profile.pk %}" class="btn btn-primary btn-sm">Abonnement</a> -->
                    </div>
                    <br>
                {% endfor %}
                
            </div>
        </div>
    </div>


{% endblock content %}